import { useState } from "react";
import {
  IndianRupee,
  Search,
  Send,
  CheckCircle,
  AlertTriangle,
  ArrowLeft,
  Clock,
  User,
  CreditCard,
  FileText,
  Download,
} from "lucide-react";
import { Link } from "react-router-dom";
import { jsPDF } from "jspdf";

function Customer() {
  const [transactionId, setTransactionId] = useState("");
  const [transaction, setTransaction] = useState(null);
  const [loading, setLoading] = useState(false);
  const [requestLoading, setRequestLoading] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [refundRequested, setRefundRequested] = useState(false);
  const [failureReason, setFailureReason] = useState("OTHER");

  const FAILURE_REASONS = [
    "INSUFFICIENT_FUNDS",
    "NETWORK_ISSUE",
    "BANK_ISSUE",
    "GATEWAY_TIMEOUT",
    "TECHNICAL_ERROR",
    "OTHER"
  ];

  // --------------------------------
  // FIND TRANSACTION
  // --------------------------------

  const findTransaction = async () => {
    if (!transactionId.trim()) {
      setError("Please enter a transaction ID.");
      return;
    }

    try {
      setLoading(true);
      setError("");
      setMessage("");
      setTransaction(null);
      setRefundRequested(false);

      const response = await fetch(
        `/api/transactions/${transactionId.trim()}`
      );

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.detail || "Transaction not found.");
      }

      setTransaction(data);
    } catch (err) {
      console.error(err);
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  // --------------------------------
  // REQUEST REFUND
  // --------------------------------

  const requestRefund = async () => {
    if (!transaction) return;

    try {
      setRequestLoading(true);
      setError("");
      setMessage("");

      const reason = `Customer requested refund for failed payment. Failure reason: ${failureReason.replaceAll("_", " ")}`;

      const response = await fetch(
        `/api/refunds?transaction_id=${transaction.transaction_id}&reason=${encodeURIComponent(reason)}`,
        {
          method: "POST",
        }
      );

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.detail || "Refund request failed.");
      }

      setRefundRequested(true);
      setMessage(
        "✅ Refund request submitted successfully! Your request is now pending admin review. You will be notified once processed."
      );

    } catch (err) {
      console.error(err);
      setError(err.message);
    } finally {
      setRequestLoading(false);
    }
  };

  // --------------------------------
  // FORMAT DATE
  // --------------------------------

  const formatDate = (date) => {
    if (!date) return "-";
    return new Date(date).toLocaleString("en-IN", {
      day: "2-digit",
      month: "short",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  };

  const downloadInvoice = () => {
    const pdf = new jsPDF();
    pdf.setFillColor(15, 23, 42);
    pdf.rect(0, 0, 210, 38, "F");
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(18);
    pdf.text("AI REVENUE RECOVERY", 18, 17);
    pdf.setFontSize(10);
    pdf.text("TRANSACTION INVOICE", 18, 27);
    pdf.setTextColor(30, 41, 59);
    pdf.setFontSize(12);
    [
      `Transaction: ${transaction.transaction_id}`,
      `Customer: ${transaction.customer_name}`,
      `Account: ${transaction.account_number}`,
      `Amount: INR ${Number(transaction.amount || 0).toLocaleString("en-IN")}`,
      `Status: ${transaction.status}`,
      `Debit status: ${transaction.debit_status}`,
      `Failure reason: ${transaction.failure_reason?.replaceAll("_", " ") || "N/A"}`,
      `Date: ${formatDate(transaction.created_at)}`,
    ].forEach((line, index) => pdf.text(line, 18, 58 + index * 13));
    pdf.setFontSize(9);
    pdf.setTextColor(100, 116, 139);
    pdf.text("Generated by AI Revenue Recovery", 18, 175);
    pdf.save(`${transaction.transaction_id}-invoice.pdf`);
  };

  // --------------------------------
  // UI
  // --------------------------------

  return (
    <div className="app">
      {/* HEADER */}
      <header className="header">
        <div>
          <h1>🤖 AI Revenue Recovery</h1>
          <p>Customer Refund Portal</p>
        </div>
        <Link to="/" className="back-button">
          <ArrowLeft size={18} />
          Home
        </Link>
      </header>

      {/* MAIN */}
      <main className="container">
        {/* HERO */}
        <section className="customer-hero">
          <h2>🔄 Request a Refund</h2>
          <p>
            Enter your transaction ID to check your payment status and request a refund
            if your account was debited for a failed payment.
          </p>
        </section>

        {/* SEARCH */}
        <section className="customer-search">
          <div className="search-box">
            <input
              type="text"
              placeholder="Enter Transaction ID e.g. TXN001"
              value={transactionId}
              onChange={(e) => setTransactionId(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter") {
                  findTransaction();
                }
              }}
            />
            <button
              onClick={findTransaction}
              disabled={loading}
              className="search-button"
            >
              <Search size={18} />
              {loading ? "Checking..." : "Find Transaction"}
            </button>
          </div>
        </section>

        {/* ERROR */}
        {error && (
          <div className="error">
            <AlertTriangle size={18} />
            {error}
          </div>
        )}

        {/* SUCCESS */}
        {message && (
          <div className="success-message">
            <CheckCircle size={18} />
            {message}
          </div>
        )}

        {/* TRANSACTION */}
        {transaction && (
          <section className="customer-transaction">
            {/* TRANSACTION HEADER */}
            <div className="transaction-header">
              <div>
                <span className="analysis-label">TRANSACTION</span>
                <h2>{transaction.transaction_id}</h2>
              </div>
              <div className="transaction-actions">
                <button className="invoice-button" type="button" onClick={downloadInvoice}>
                  <Download size={16} />
                  Invoice PDF
                </button>
                <span className={`badge ${transaction.status === "REFUNDED" ? "success-badge" : transaction.status === "SUCCESS" ? "success-badge" : "failed-badge"}`}>
                  {transaction.status}
                </span>
              </div>
            </div>

            {/* DETAILS */}
            <div className="customer-details">
              <div>
                <span><User size={14} /> Customer</span>
                <strong>{transaction.customer_name}</strong>
              </div>
              <div>
                <span><CreditCard size={14} /> Account</span>
                <strong>{transaction.account_number}</strong>
              </div>
              <div>
                <span><IndianRupee size={14} /> Amount</span>
                <strong>₹{Number(transaction.amount).toLocaleString("en-IN")}</strong>
              </div>
              <div>
                <span><FileText size={14} /> Failure Reason</span>
                <strong>{transaction.failure_reason?.replaceAll("_", " ") || "N/A"}</strong>
              </div>
              <div>
                <span>Debit Status</span>
                <strong>
                  <span className={`badge ${transaction.debit_status === "DEBITED" ? "failed-badge" : transaction.debit_status === "PARTIAL" ? "pending-badge" : "success-badge"}`}>
                    {transaction.debit_status}
                  </span>
                </strong>
              </div>
              <div>
                <span>Date</span>
                <strong>{formatDate(transaction.created_at)}</strong>
              </div>
            </div>

            {/* AI ANALYSIS RESULTS */}
            {transaction.risk_score && (
              <div className="ai-analysis-summary">
                <h4>🤖 AI Analysis</h4>
                <div className="ai-summary-grid">
                  <div>
                    <span>Risk Score</span>
                    <span className={`risk-score-badge ${transaction.risk_score < 40 ? "low-risk" : transaction.risk_score < 70 ? "medium-risk" : "high-risk"}`}>
                      {transaction.risk_score}%
                    </span>
                  </div>
                  <div>
                    <span>Recovery Action</span>
                    <span className={`recommended-action-display ${transaction.recovery_action === "REFUND" ? "refund-action" : transaction.recovery_action === "REVIEW" ? "review-action" : "reject-action"}`}>
                      {transaction.recovery_action}
                    </span>
                  </div>
                  <div>
                    <span>AI Confidence</span>
                    <span>{transaction.ai_confidence || 85}%</span>
                  </div>
                </div>
              </div>
            )}

            {/* =========================
                REFUND ELIGIBILITY
            ========================== */}

            {refundRequested ? (
              <div className="refund-request-box">
                <div>
                  <h3>
                    <Clock size={20} />
                    Refund Request Pending
                  </h3>
                  <p>
                    Your refund request has been submitted successfully and is waiting for admin review.
                    You will receive a notification once it's processed.
                  </p>
                </div>
                <span className="badge pending-badge">PENDING</span>
              </div>
            ) : transaction.status === "FAILED" && transaction.debit_status === "DEBITED" ? (
              <div className="refund-request-box">
                <div>
                  <h3>💰 Money was debited</h3>
                  <p>
                    Your payment failed but the amount was deducted from your account.
                    You can submit a refund request for admin review.
                  </p>
                  <div className="failure-reason-select">
                    <label>Failure Reason:</label>
                    <select
                      value={failureReason}
                      onChange={(e) => setFailureReason(e.target.value)}
                    >
                      {FAILURE_REASONS.map((reason) => (
                        <option key={reason} value={reason}>
                          {reason.replaceAll("_", " ")}
                        </option>
                      ))}
                    </select>
                  </div>
                </div>
                <button
                  className="approve-button"
                  onClick={requestRefund}
                  disabled={requestLoading}
                >
                  <Send size={17} />
                  {requestLoading ? "Submitting..." : "Request Refund"}
                </button>
              </div>
            ) : transaction.status === "REFUNDED" ? (
              <div className="success-message">
                <CheckCircle size={18} />
                ✅ This transaction has already been refunded. The amount has been credited back to your account.
              </div>
            ) : transaction.status === "SUCCESS" ? (
              <div className="warning-message">
                <CheckCircle size={18} style={{ color: "#10b981" }} />
                ✅ This transaction was successful. No refund needed.
              </div>
            ) : (
              <div className="warning-message">
                <AlertTriangle size={18} />
                This transaction is not currently eligible for a refund request because the payment was not debited or did not fail.
              </div>
            )}
          </section>
        )}
      </main>
    </div>
  );
}

export default Customer;